=== uo287568/SEW-EXTRA-2025/xml/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta  (nombre, transporte, personas-adecuadas, detalles-ruta, hitos, referencias, kml, svg)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT transporte (#PCDATA)>
<!ELEMENT personas-adecuadas (#PCDATA)>
<!ELEMENT detalles-ruta (fecha-inicio, hora-inicio, descripción, lugar-inicio)>
<!ELEMENT fecha-inicio (#PCDATA)>
<!ELEMENT hora-inicio (#PCDATA)>
<!ELEMENT descripción (acciones, elementos)>
<!ELEMENT acciones (acción+)>
<!ELEMENT acción (#PCDATA)>
<!ELEMENT elementos (elemento+)>
<!ELEMENT elemento (#PCDATA)>
<!ELEMENT lugar-inicio (lugar, dirección, coordenadas)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT dirección (#PCDATA)>
<!ELEMENT coordenadas (#PCDATA)>
<!ELEMENT hitos (hito+)>
<!ELEMENT hito (nombre, descripción-hito, distancia-hito, coordenadas, fotos, videos?)>
<!ELEMENT descripción-hito (#PCDATA)>
<!ELEMENT distancia-hito (#PCDATA)>
<!ELEMENT fotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT videos (video*)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT kml (#PCDATA)>
<!ELEMENT svg (#PCDATA)>
<!ATTLIST ruta 
    type CDATA #REQUIRED
    recomendación CDATA #REQUIRED>
<!ATTLIST detalles-ruta 
    agencia CDATA #REQUIRED
    duración-horas CDATA #REQUIRED>
<!ATTLIST elemento incluido CDATA #REQUIRED>
<!ATTLIST coordenadas 
    longitud CDATA #REQUIRED
    latitud CDATA #REQUIRED
    altitud-metros CDATA #REQUIRED>
<!ATTLIST coordenadas-hito
    longitud CDATA #REQUIRED
    latitud CDATA #REQUIRED
    altitud-metros CDATA #REQUIRED>
<!ATTLIST distancia-hito unidad CDATA #REQUIRED>

=== uo287568/SEW-EXTRA-2025/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
	<ruta type="Paisajística // Histórica" recomendación="8">
		<nombre>Ruta del Ferrocarril en San Tirso de Abres</nombre>
		<transporte>A pie y en bicicleta</transporte>
        <personas-adecuadas>Para todo tipo de público. Accesible en silla de ruedas</personas-adecuadas>
		<detalles-ruta agencia="Turismo Asturias" duración-horas="4">
			<fecha-inicio>15/07/2025</fecha-inicio>
            <hora-inicio>10:00</hora-inicio>
            <descripción>
                <acciones>
                    <acción>Recorre el antiguo trazado del ferrocarril minero que operó hasta 1964, 
                        atravesando túneles y disfrutando de la frondosa vegetación junto al río Eo.</acción>
                    <acción>Conoce la historia del ferrocarril en la zona y su importancia para la 
                        minería y el desarrollo local.</acción>
                    <acción>Disfruta de un recorrido accesible y seguro, ideal para ciclistas y senderistas, 
                        con paneles informativos a lo largo del trayecto.</acción>
                </acciones>
                <elementos>
                    <elemento incluido="Si">Casco minero</elemento>
                    <elemento incluido="Si">Chaleco reflectante</elemento>
                    <elemento incluido="No">Bicicletas</elemento>
                    <elemento incluido="No">Comida y bebidas</elemento>
                </elementos>
            </descripción>
            <lugar-inicio>
                <lugar>San Tirso de Abres</lugar>
                <dirección>Área recreativa junto al puente sobre el río Eo.</dirección>
                <coordenadas longitud="-7.142427354257823" latitud="43.41033916846158" altitud-metros="36"/>
            </lugar-inicio>
		</detalles-ruta>
		<hitos>
            <hito>
                <nombre>Túneles del antiguo ferrocarril</nombre>
                <descripción-hito>Pasajes históricos excavados en la roca, utilizados para el paso del 
                    tren minero.</descripción-hito>
                <distancia-hito unidad="metros">610</distancia-hito>
                <coordenadas longitud="-7.149012377722078" latitud="43.41299549370026" altitud-metros="62"/>
                <fotos>
                    <foto>multimedia/imagenes/TunelFerrocarril.jpg</foto>
                </fotos>
            </hito>
            <hito>
                <nombre>Río Eo</nombre>
                <descripción-hito>Acompaña gran parte del recorrido, ofreciendo paisajes naturales 
                    de gran belleza y zonas de descanso.</descripción-hito>
                <distancia-hito unidad="metros">420</distancia-hito>
                <coordenadas longitud="-7.154012531993898" latitud="43.41201713078001" altitud-metros="37"/>
                <fotos>
                    <foto>multimedia/imagenes/RioEo.jpg</foto>
                </fotos>
            </hito>
            <hito>
                <nombre>Centro de la Pesca</nombre>
                <descripción-hito>Espacio que ofrece información sobre la historia pesquera de la 
                    región y la importancia del río Eo.</descripción-hito>
                <distancia-hito unidad="metros">840</distancia-hito>
                <coordenadas longitud="-7.164350591784718" latitud="43.41155041987275" altitud-metros="42"/>
                <fotos>
                    <foto>multimedia/imagenes/CentroPesca.jpg</foto>
                </fotos>
            </hito>
            <hito>
                <nombre>Antigua central eléctrica</nombre>
                <descripción-hito>Construida en 1932 situada justo antes de atravesar otro de los túneles 
                    horadados en la roca viva, que nos deja próximos a la pasarela peatonal sobre el Río Eo.</descripción-hito>
                <distancia-hito unidad="metros">1140</distancia-hito>
                <coordenadas longitud="-7.170814650176813" latitud="43.402485015918934" altitud-metros="62"/>
                <fotos>
                    <foto>multimedia/imagenes/CentralElectrica.jpg</foto>
                </fotos>
            </hito>
            <hito>
                <nombre>Casetos</nombre>
                <descripción-hito>Pequeñas construcciones de mampostería, con cubierta de pizarra a dos aguas 
                    que servían para albergar el carbón usado por el ferrocarril.</descripción-hito>
                <distancia-hito unidad="metros">670</distancia-hito>
                <coordenadas longitud="-7.163097633717294" latitud="43.40021610623295" altitud-metros="220"/>
                <fotos>
                    <foto>multimedia/imagenes/Caseto.jpg</foto>
                </fotos>
            </hito>
        </hitos>
        <referencias>
			<referencia>https://www.turismoasturias.es/descubre/donde-ir/municipios/san-tirso-de-abres</referencia>
            <referencia>https://www.santirsodeabres.es/en/ruta-del-ferrocarril</referencia>
            <referencia>https://es.wikiloc.com/rutas-senderismo/ruta-del-ferrocarril-a-pontenova-san-tirso-de-abres-nueva-version-74106882</referencia>
        </referencias>
        <kml>xml/ruta1.kml</kml>
        <svg>xml/perfil1.svg</svg>
	</ruta>
    <ruta type="Senderismo // Naturaleza" recomendación="9">
		<nombre>Ruta de la Peña del Encanto</nombre>
		<transporte>A pie</transporte>
        <personas-adecuadas>Para senderistas con experiencia media. No recomendada para personas con movilidad reducida.</personas-adecuadas>
		<detalles-ruta agencia="Turismo de San Tirso" duración-horas="3">
			<fecha-inicio>17/07/2025</fecha-inicio>
            <hora-inicio>10:15</hora-inicio>
            <descripción>
                <acciones>
                    <acción>La Ruta de la Peña del Encanto es un recorrido de senderismo que permite adentrarse en un paisaje natural impresionante, siguiendo antiguas sendas utilizadas por pastores y lugareños.</acción>
                    <acción>El sendero discurre entre bosques autóctonos y afloramientos rocosos, ofreciendo vistas espectaculares del valle del río Eo.</acción>
                    <acción>El punto culminante es la Peña del Encanto, una formación rocosa envuelta en leyendas locales sobre seres mágicos y antiguos rituales.</acción>
                </acciones>
                <elementos>
                    <elemento incluido="Si">Mapa de la ruta</elemento>
                    <elemento incluido="Si">Seguro de accidentes</elemento>
                    <elemento incluido="No">Guía turístico</elemento>
                    <elemento incluido="No">Comida y bebidas</elemento>
                </elementos>
            </descripción>
            <lugar-inicio>
                <lugar>Plaza del Ayuntamiento</lugar>
                <dirección>Plaza del Ayuntamiento, 1, 33774 San Tirso de Abres, Asturias, España</dirección>
                <coordenadas longitud="-7.151697983753063" latitud="43.412540303203926" altitud-metros="74"/>
            </lugar-inicio>
		</detalles-ruta>
		<hitos>
            <hito>
                <nombre>Puente medieval de San Tirso</nombre>
                <descripción-hito>Antiguo puente de piedra que formaba parte de una ruta de comunicación 
                    histórica entre Asturias y Galicia.</descripción-hito>
                <distancia-hito unidad="metros">700</distancia-hito>
                <coordenadas longitud="-7.153412281575685" latitud="43.41871726100285" altitud-metros="85"/>
                <fotos>
                    <foto>multimedia/imagenes/PuenteMedieval.jpg</foto>
                </fotos>
            </hito>
            <hito>
                <nombre>Arroyo de Ramalledo</nombre>
                <descripción-hito>Encargado de regar numerosos bosquetes de flora autóctona 
                    que se asientan a lo largo de su curso.</descripción-hito>
                <distancia-hito unidad="metros">350</distancia-hito>
                <coordenadas longitud="-7.157246698865485" latitud="43.42014305099363" altitud-metros="100"/>
                <fotos>
                    <foto>multimedia/imagenes/ArroyoRamalledo.jpg</foto>
                </fotos>
            </hito>
            <hito>
                <nombre>Pena do Encanto</nombre>
                <descripción-hito>Zona donde fluye una misteriosa cascada fundida entre agua y piedra, 
                    en la que aún late la leyenda de una dama encantada que sale de la roca con un 
                    peine de plata cada noche de San Juan para hechizar a quien la vea.</descripción-hito>
                <distancia-hito unidad="metros">870</distancia-hito>
                <coordenadas longitud="-7.167726154339583" latitud="43.42174132962535" altitud-metros="213"/>
                <fotos>
                    <foto>multimedia/imagenes/PenaEncanto.jpg</foto>
                </fotos>
            </hito>
            <hito>
                <nombre>Mirador de la Peña del Encanto</nombre>
                <descripción-hito>Un impresionante mirador natural con vistas panorámicas del valle 
                    y el río Eo.</descripción-hito>
                <distancia-hito unidad="metros">540</distancia-hito>
                <coordenadas longitud="-7.167211170147849" latitud="43.41687861264646" altitud-metros="281"/>
                <fotos>
                    <foto>multimedia/imagenes/MiradorPenaEncanto.jpg</foto>
                </fotos>
            </hito>
            <hito>
                <nombre>Vilela de Arriba</nombre>
                <descripción-hito>Tramo en el que observaremos la capital municipal en la zona conocida como el Llano, 
                    asentada sobre un valle rodeado de suaves montañas.</descripción-hito>
                <distancia-hito unidad="metros">890</distancia-hito>
